"""Generate test scenario input files and their expected outputs.

Each scenario is a directory in tests/scenarios/<name>/ containing:
    input.json       — financial data (W2, 1099, 1098, etc.)
    data.json        — expected forms_state (generated by running computation)
    worksheets.json  — expected worksheets (generated)
    summary.json     — expected summary (generated)

To add a scenario: add an entry to the SCENARIOS dict below and re-run this script.
To regenerate all expected outputs: python tests/generate_scenarios.py

Scenarios:
    w2_only               — W2 wages only, no 1099/investments
    capital_loss           — short-term loss exceeding $3k deduction limit
    capital_loss_carryover — prior-year losses carried forward via prior_year dict
    estimated_payments     — federal and state estimated tax payments
    no_mortgage            — 1099 interest/dividends, no mortgage deduction
    itemized_wins          — high state tax + mortgage + property tax beats standard deduction
    foreign_tax            — foreign tax paid triggers Schedule 3 credit
    contract_1256          — Section 1256 futures contracts via Form 6781
    many_trades            — 20 trades across short/long term, multiple 8949 pages
"""
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from tests.test_computation import load_scenario_input
from utils.forms_core_2025 import fill_taxes_2025

SCENARIOS_DIR = os.path.join(os.path.dirname(__file__), 'scenarios')

# Minimal W2 used by all scenarios
BASE_W2 = {
    "Company": "Good Company & CO LLC",
    "Company_address": "100 100TH AVE",
    "Company_city": "NEW YORK",
    "Company_state": "NY",
    "Company_zip": "10000",
    "FullName": "Commando French",
    "FirstName": "French",
    "LastName": "Commando",
    "Address": "111 111TH ST",
    "Address_apt": "11A",
    "Address_city": "BROOKLYN",
    "Address_state": "NY",
    "Address_zip": "11111",
    "SSN": "XXXXX5555",
    "Wages": 150000,
    "SocialSecurity_wages": 150000,
    "Medicare_wages": 150000,
    "Federal_tax": 30000,
    "SocialSecurity_tax": 9300,
    "Medicare_tax": 2175,
    "State": "NY",
    "State_tax": 7000,
    "Local_tax": 3000,
    "Locality": "NEW YORK",
}

SCENARIOS = {
    "w2_only": {
        "W2": [BASE_W2],
    },
    "capital_loss": {
        "W2": [BASE_W2],
        "1099": [
            {
                "Interest": 50,
                "Institution": "Big Bank",
                "Trades": [
                    {
                        "SalesDescription": "LOSING STOCK",
                        "Shares": "100",
                        "DateAcquired": "2025/01/15",
                        "DateSold": "2025/06/15",
                        "Proceeds": 5000,
                        "Cost": 12000,
                        "LongShort": "SHORT",
                        "FormCode": "A",
                    },
                ],
            },
        ],
    },
    "capital_loss_carryover": {
        "W2": [BASE_W2],
        "prior_year": {
            "taxable_income": 100000,
            "schedule_d_net_short_term": -8000,
            "schedule_d_net_long_term": -2000,
            "schedule_d_loss_deduction": 3000,
        },
        "1099": [
            {
                "Interest": 100,
                "Institution": "Some Bank",
                "Trades": [
                    {
                        "SalesDescription": "SOME STOCK",
                        "Shares": "50",
                        "DateAcquired": "2025/03/01",
                        "DateSold": "2025/09/01",
                        "Proceeds": 10000,
                        "Cost": 9000,
                        "LongShort": "SHORT",
                        "FormCode": "A",
                    },
                ],
            },
        ],
    },
    "estimated_payments": {
        "W2": [BASE_W2],
        "1099": [
            {
                "Interest": 500,
                "Institution": "Some Bank",
            },
        ],
        "EstimatedIncomeTax": {
            "Federal": [
                {"Date": "2025/04/15", "Amount": 5000},
                {"Date": "2025/06/15", "Amount": 5000},
            ],
            "State": [
                {"Date": "2025/04/15", "Amount": 2000},
            ],
        },
    },
    "no_mortgage": {
        "W2": [BASE_W2],
        "1099": [
            {
                "Interest": 500,
                "Qualified Dividends": 1000,
                "Ordinary Dividends": 1500,
                "Institution": "Brokerage Inc",
            },
        ],
    },
    "itemized_wins": {
        "W2": [{**BASE_W2, "State_tax": 15000, "Local_tax": 8000}],
        "1098": [
            {
                "Payments": [
                    {"Date": "2025/06/01", "InterestAmount": 12000, "PrincipalAmount": 2000},
                    {"Date": "2025/12/01", "InterestAmount": 12000, "PrincipalAmount": 2000},
                ],
                "PrincipalBalance": 500000,
                "LoanNumber": "123456",
                "Recipient": "Mortgage Bank",
            },
        ],
        "Other": [{"PropertyTax": 8000, "CoopStateTaxes": 100}],
    },
    "foreign_tax": {
        "W2": [BASE_W2],
        "1099": [
            {
                "Interest": 200,
                "Qualified Dividends": 3000,
                "Ordinary Dividends": 5000,
                "Foreign Tax Paid": 500,
                "Foreign Country": "Various",
                "Institution": "International Fund",
            },
        ],
    },
    "contract_1256": {
        "W2": [BASE_W2],
        "1099": [
            {
                "Institution": "Futures Broker",
                "Interest": 0,
                "Contract1256": [
                    {"ProfitOrLoss": 15000},
                    {"ProfitOrLoss": -3000},
                ],
                "Trades": [],
            },
        ],
    },
    "many_trades": {
        "W2": [BASE_W2],
        "1099": [
            {
                "Interest": 100,
                "Institution": "Active Broker",
                "Trades": [
                    {
                        "SalesDescription": f"STOCK {i}",
                        "Shares": "10",
                        "DateAcquired": f"2025/0{(i % 9) + 1}/01",
                        "DateSold": f"2025/{((i + 3) % 12) + 1:02d}/15",
                        "Proceeds": 1000 + i * 100,
                        "Cost": 900 + i * 100,
                        "LongShort": "SHORT" if i < 10 else "LONG",
                        "FormCode": "B" if i < 10 else "E",
                    }
                    for i in range(20)
                ],
            },
        ],
    },
}


def generate_all():
    for name, input_data in SCENARIOS.items():
        scenario_dir = os.path.join(SCENARIOS_DIR, name)
        os.makedirs(scenario_dir, exist_ok=True)

        with open(os.path.join(scenario_dir, 'input.json'), 'w') as f:
            json.dump(input_data, f, indent=4)

        data = load_scenario_input(scenario_dir)
        states, worksheets, summary, carryover = fill_taxes_2025(d=data)
        for out_name, out_data in [('data', states), ('worksheets', worksheets), ('summary', summary), ('carryover', carryover)]:
            with open(os.path.join(scenario_dir, f'{out_name}.json'), 'w') as f:
                json.dump(out_data, f, indent=4)

        print(f'Generated: {name}')


if __name__ == '__main__':
    generate_all()
