"""Tax computation tests.

Each test is a scenario in tests/scenarios/<year>/<name>/ containing:
    input.json       - financial data (W2, 1099, 1098, etc.)
    data.json        - expected forms_state output (all form field values)
    worksheets.json  - expected worksheet computations
    summary.json     - expected summary of key figures
    carryover.json   - expected carryover values for next year

The test runner discovers year subfolders under tests/scenarios/, then
discovers scenario directories within each year. It loads the input,
merges it with filing defaults (single, no dependents, etc.), runs the
year-specific computation, and asserts the output matches the expected
files exactly.

Scenarios are generated by tests/generate_scenarios_<year>.py.
To add a new scenario: add it to SCENARIOS in the appropriate generator and re-run it.

Run: python -m unittest tests.test_computation -v
"""
import json
import os
import unittest

from utils.forms_constants import override_keyword
from pipeline.fill_taxes import FILL_FUNCTIONS
from computation.forms_core_impl import extract_carryover

SCENARIOS_DIR = os.path.join(os.path.dirname(__file__), 'scenarios')

# Filing defaults applied to every scenario.
# Scenarios can override these by including the same keys in input.json.
DEFAULTS = {
    'single': True,
    'dependents': False,
    'occupation': "Analyst",
    'full_year_health_coverage_or_exempt': True,
    'presidential_election_self': False,
    'resident': True,
    'scheduleD': True,
    'checking': True,
    'routing_number': "11111111",
    'account_number': "444444444",
    'phone': '6465555555',
    'email': 'test@test.com',
    'health_savings_account': False,
    'health_savings_account_contributions': 0,
    'health_savings_account_employer_contributions': 0,
    'health_savings_account_distributions': 0,
    'medical_expenses': 0,
    'virtual_currency': False,
}


def load_scenario_input(scenario_dir):
    with open(os.path.join(scenario_dir, 'input.json'), 'r') as f:
        j = json.load(f)

    data = {}
    data.update(j)
    data.update(DEFAULTS)
    # allow input.json to override defaults
    data.update(j)

    data[override_keyword] = {
        'address_street_and_number': next(iter(j['W2']))['Address'],
        'address_apt': next(iter(j['W2']))['Address_apt'],
        'address_city': next(iter(j['W2']))['Address_city'],
        'address_state': next(iter(j['W2']))['Address_state'],
        'address_zip': next(iter(j['W2']))['Address_zip'],
        'ssn': '200112222',
    }

    return data


def run_fill(year, data):
    """Run the year-specific fill function, normalizing the return to a 4-tuple."""
    fill_func = FILL_FUNCTIONS[year]
    if year == "2023":
        states, worksheets, summary = fill_func(d=data, output_2022=None)
        carryover = extract_carryover(states)
    else:
        states, worksheets, summary, carryover = fill_func(d=data)
    return states, worksheets, summary, carryover


def load_expected(scenario_dir):
    expected = {}
    for name in ('data', 'worksheets', 'summary', 'carryover'):
        path = os.path.join(scenario_dir, f'{name}.json')
        with open(path, 'r') as f:
            expected[name] = json.load(f)
    return expected


class TestComputation(unittest.TestCase):
    pass


def make_test(scenario_name, scenario_dir, year):
    def test(self):
        data = load_scenario_input(scenario_dir)
        states, worksheets, summary, carryover = run_fill(year, data)
        expected = load_expected(scenario_dir)
        self.assertEqual(states, expected['data'], f'{scenario_name}: forms_state mismatch')
        self.assertEqual(worksheets, expected['worksheets'], f'{scenario_name}: worksheets mismatch')
        self.assertEqual(summary, expected['summary'], f'{scenario_name}: summary mismatch')
        self.assertEqual(carryover, expected['carryover'], f'{scenario_name}: carryover mismatch')
    return test


# Discover year folders and scenarios within each, generate test methods
for year_entry in sorted(os.listdir(SCENARIOS_DIR)):
    year_path = os.path.join(SCENARIOS_DIR, year_entry)
    if not os.path.isdir(year_path) or year_entry not in FILL_FUNCTIONS:
        continue
    for entry in sorted(os.listdir(year_path)):
        scenario_path = os.path.join(year_path, entry)
        if os.path.isdir(scenario_path) and os.path.exists(os.path.join(scenario_path, 'input.json')):
            test_method = make_test(entry, scenario_path, year_entry)
            test_method.__name__ = f'test_{year_entry}_{entry}'
            setattr(TestComputation, f'test_{year_entry}_{entry}', test_method)


class TestRealData(unittest.TestCase):
    """Verify that computing from real input_data/ matches the committed output JSONs."""

    def test_real_data(self):
        from pipeline.fill_taxes import gather_inputs
        from utils.forms_constants import json_extension

        years = ["2023", "2024", "2025"]
        carryover = None
        for year in years:
            data = gather_inputs(year)
            if carryover is not None:
                data['prior_year'] = carryover

            states, worksheets, summary, carryover = run_fill(year, data)

            for name, actual in [('data', states), ('worksheet', worksheets), ('summary', summary), ('carryover', carryover)]:
                with open(os.path.join("output", year, name + json_extension), 'r') as f:
                    expected = json.load(f)
                self.assertEqual(actual, expected, f'{name}{year}: mismatch')


if __name__ == '__main__':
    unittest.main()
