"""Tax computation tests.

Each test is a scenario in tests/scenarios/<name>/ containing:
    input.json       — financial data (W2, 1099, 1098, etc.)
    data.json        — expected forms_state output (all form field values)
    worksheets.json  — expected worksheet computations
    summary.json     — expected summary of key figures

The test runner discovers all scenario directories, loads the input,
merges it with filing defaults (single, no dependents, etc.), runs the
2025 computation, and asserts the output matches the expected files exactly.

Scenarios are generated by tests/generate_scenarios.py.
To add a new scenario: add it to SCENARIOS in generate_scenarios.py and re-run it.

Run: python -m unittest tests.test_computation -v
"""
import json
import os
import unittest

from utils.forms_constants import override_keyword
from utils.forms_core_2025 import fill_taxes_2025

SCENARIOS_DIR = os.path.join(os.path.dirname(__file__), 'scenarios')

# Filing defaults applied to every scenario.
# Scenarios can override these by including the same keys in input.json.
DEFAULTS = {
    'single': True,
    'dependents': False,
    'occupation': "Analyst",
    'full_year_health_coverage_or_exempt': True,
    'presidential_election_self': False,
    'resident': True,
    'scheduleD': True,
    'checking': True,
    'routing_number': "11111111",
    'account_number': "444444444",
    'phone': '6465555555',
    'email': 'test@test.com',
    'health_savings_account': False,
    'health_savings_account_contributions': 0,
    'health_savings_account_employer_contributions': 0,
    'health_savings_account_distributions': 0,
    'medical_expenses': 0,
    'virtual_currency': False,
}


def load_scenario_input(scenario_dir):
    with open(os.path.join(scenario_dir, 'input.json'), 'r') as f:
        j = json.load(f)

    data = {}
    data.update(j)
    data.update(DEFAULTS)
    # allow input.json to override defaults
    data.update(j)

    data[override_keyword] = {
        'address_street_and_number': next(iter(j['W2']))['Address'],
        'address_apt': next(iter(j['W2']))['Address_apt'],
        'address_city': next(iter(j['W2']))['Address_city'],
        'address_state': next(iter(j['W2']))['Address_state'],
        'address_zip': next(iter(j['W2']))['Address_zip'],
        'ssn': '200112222',
    }

    return data


def load_expected(scenario_dir):
    expected = {}
    for name in ('data', 'worksheets', 'summary'):
        path = os.path.join(scenario_dir, f'{name}.json')
        with open(path, 'r') as f:
            expected[name] = json.load(f)
    return expected


class TestComputation(unittest.TestCase):
    pass


def make_test(scenario_name, scenario_dir):
    def test(self):
        data = load_scenario_input(scenario_dir)
        states, worksheets, summary, _carryover = fill_taxes_2025(d=data)
        expected = load_expected(scenario_dir)
        self.assertEqual(states, expected['data'], f'{scenario_name}: forms_state mismatch')
        self.assertEqual(worksheets, expected['worksheets'], f'{scenario_name}: worksheets mismatch')
        self.assertEqual(summary, expected['summary'], f'{scenario_name}: summary mismatch')
    return test


# Discover scenarios and generate test methods
for entry in sorted(os.listdir(SCENARIOS_DIR)):
    scenario_path = os.path.join(SCENARIOS_DIR, entry)
    if os.path.isdir(scenario_path) and os.path.exists(os.path.join(scenario_path, 'input.json')):
        test_method = make_test(entry, scenario_path)
        test_method.__name__ = f'test_{entry}'
        setattr(TestComputation, f'test_{entry}', test_method)


if __name__ == '__main__':
    unittest.main()
